linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - always_use_package_imports
    - annotate_overrides
    - await_only_futures
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_function_literals_in_foreach_calls
    - avoid_private_typedef_functions
    - avoid_types_on_closure_parameters
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - lowercase_with_underscores
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - prefer_void_to_null
    - sort_constructors_first
    - sort_child_properties_last
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - prefer_final_fields
    - avoid_redundant_argument_values
    - use_super_parameters
    - unawaited_futures
    - unnecessary_final
    - unnecessary_parenthesis
    - use_key_in_widget_constructors
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore
    todo: warning
